apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
        - name: products-service
          image: rustembayetov/products_service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:                  # Environment variables supplied to the Pod
            - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
              valueFrom:          # Get the value of environment variable from kubernetes secrets
                secretKeyRef:
                  name: mysql-products-service-secrets
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-products-service-secrets
                  key: MYSQL_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-products-service-secrets
                  key: MYSQL_URL
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-products-service-secrets
                  key: SERVER_PORT
            - name: jwt-secret
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: jwt-secret
            - name: service-secret
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: service-secret
  selector:
    matchLabels:
      app: products-service
