apiVersion: v1
kind: Secret
metadata:
  name: mysql-products-service-secrets
type: Opaque
data:
  MYSQL_USER: c2E=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_URL: amRiYzpteXNxbDovL215c3FsOjMzMDYvcHJvZHVjdHM=
  SERVER_PORT: ODA4MA==