apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: products-service