apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-service
  labels:
    app: ship-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ship-service
    spec:
      containers:
        - name: ship-service
          image: rustembayetov/ship_service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: jwt-secret
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: jwt-secret
            - name: service-secret
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: service-secret
  selector:
    matchLabels:
      app: ship-service
