apiVersion: v1
kind: Service
metadata:
  name: pays-pp-service
  labels:
    app: pays-pp-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pays-pp-service